export const REVIEW_UI = `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ContinuityDB review inbox</title>
<style>
:root{color-scheme:dark;--bg:#0b1020;--card:#151c31;--muted:#9aa6bf;--line:#29334d;--accent:#78dce8;--danger:#ff6b7a}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#edf2ff;font:14px/1.5 ui-sans-serif,system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:28px}h1,h2{margin:.2rem 0 1rem}p{color:var(--muted)}nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}button,input,textarea,select{font:inherit;color:inherit;background:#0f1628;border:1px solid var(--line);border-radius:7px;padding:9px}button{cursor:pointer}button.primary{background:#164f59;border-color:#277986}button.danger{color:#ffd4d9;border-color:#6d2934}.grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,1fr);gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px;margin-bottom:12px}.memory{cursor:pointer}.memory:hover{border-color:var(--accent)}.badge{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:2px 8px;margin-right:5px;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0a0f1d;padding:12px;border-radius:7px;max-height:420px;overflow:auto}label{display:block;margin:10px 0 4px;color:var(--muted)}input,textarea{width:100%}textarea{min-height:88px}.actions{display:flex;gap:8px;margin-top:12px}.error{color:var(--danger)}@media(max-width:800px){.grid{grid-template-columns:1fr}}
</style>
<main>
<h1>ContinuityDB review inbox</h1>
<p>Inspect provenance, approve or reject held memories, and preview exactly what an authorized agent receives.</p>
<nav><button id="refresh" class="primary">Refresh inbox</button><span id="status"></span></nav>
<div class="grid"><section><h2>Pending review</h2><div id="inbox"></div></section><section><h2>Inspection</h2><div id="detail" class="card"><p>Select a memory.</p></div><h2>Context preview</h2><div class="card"><label>Project</label><input id="project"><label>Branch</label><input id="branch"><label>Developer question/task</label><textarea id="task"></textarea><div class="actions"><button id="preview" class="primary">Build preview</button></div><pre id="preview-output"></pre></div></section></div>
</main>
<script type="module">
const $=id=>document.getElementById(id);let selected=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const value=await response.json();if(!response.ok)throw new Error(value.error||('HTTP '+response.status));return value}
async function refresh(){try{$('status').textContent='Loading…';const value=await api('/v1/memories?status=proposed,quarantined&limit=200');$('inbox').innerHTML=value.memories.map(m=>'<article class="card memory" data-id="'+esc(m.id)+'"><b>'+esc(m.title)+'</b><p><span class="badge">'+esc(m.status)+'</span><span class="badge">'+esc(m.project_id||'global')+'</span><span class="badge">'+esc(m.branch||'all branches')+'</span></p><small>'+esc(m.updated_at)+'</small></article>').join('')||'<p>No held memories.</p>';document.querySelectorAll('.memory').forEach(node=>node.onclick=()=>inspect(node.dataset.id));$('status').textContent=value.memories.length+' item(s)'}catch(error){$('status').innerHTML='<span class="error">'+esc(error.message)+'</span>'}}
async function inspect(id){try{selected=await api('/v1/memories/'+encodeURIComponent(id)+'?include_inactive=true');const m=selected;$('project').value=m.project_id||'';$('branch').value=m.branch||'';$('detail').innerHTML='<p><span class="badge">'+esc(m.status)+'</span> <span class="badge">'+esc(m.source_type)+'</span></p><label>Title</label><input id="edit-title" value="'+esc(m.title)+'"><label>Body</label><textarea id="edit-body">'+esc(m.body)+'</textarea><label>Branch scope</label><input id="edit-branch" value="'+esc(m.branch||'')+'"><details open><summary>Provenance and metadata</summary><pre>'+esc(JSON.stringify({source_uri:m.source_uri,repo_path:m.repo_path,symbol:m.symbol,git_commit:m.git_commit,branch:m.branch,observed_at:m.observed_at,metadata:JSON.parse(m.metadata_json||'{}')},null,2))+'</pre></details><div class="actions"><button id="save">Save correction</button><button id="approve" class="primary">Approve</button><button id="reject" class="danger">Reject</button></div>';$('save').onclick=saveRevision;$('approve').onclick=()=>act('approve');$('reject').onclick=()=>act('reject')}catch(error){$('detail').innerHTML='<p class="error">'+esc(error.message)+'</p>'}}
async function saveRevision(){if(!selected)return;try{await api('/v1/memories/'+encodeURIComponent(selected.id)+'/revisions',{method:'POST',body:JSON.stringify({reason:'review-ui correction',replacement:{title:$('edit-title').value,body:$('edit-body').value,branch:$('edit-branch').value||null}})});await inspect(selected.id);await refresh()}catch(error){$('detail').innerHTML+='<p class="error">'+esc(error.message)+'</p>'}}
async function act(action){if(!selected)return;try{if(action==='approve')await api('/v1/memories/'+encodeURIComponent(selected.id)+'/commit',{method:'POST'});else await api('/v1/memories/'+encodeURIComponent(selected.id),{method:'DELETE'});selected=null;$('detail').innerHTML='<p>Done.</p>';await refresh()}catch(error){$('detail').innerHTML+='<p class="error">'+esc(error.message)+'</p>'}}
$('preview').onclick=async()=>{try{const value=await api('/v1/context-packs',{method:'POST',body:JSON.stringify({project_id:$('project').value||null,branch:$('branch').value||null,task:$('task').value,token_budget:1200})});$('preview-output').textContent=JSON.stringify(value,null,2)}catch(error){$('preview-output').textContent=error.message}};$('refresh').onclick=refresh;refresh();
</script>
</html>`;
